// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PametniDomAPP;

#nullable disable

namespace PametniDomApplikacija.Migrations
{
    [DbContext(typeof(StockContext))]
    [Migration("20240106121224_M9")]
    partial class M9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("PametniDomAPP.Naprava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("n_ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("prvic_povezan")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NapravaDB");
                });

            modelBuilder.Entity("PametniDomAPP.Obvestilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum_obvestila")
                        .HasColumnType("TEXT");

                    b.Property<int>("NapravaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("vsebina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NapravaId");

                    b.ToTable("ObvestiloDB");
                });

            modelBuilder.Entity("PametniDomAPP.Uporabnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("geslo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("uenaslov")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("uime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UporabnikDB");
                });

            modelBuilder.Entity("PametniDomAPP.Obvestilo", b =>
                {
                    b.HasOne("PametniDomAPP.Naprava", "Naprava")
                        .WithMany()
                        .HasForeignKey("NapravaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Naprava");
                });
#pragma warning restore 612, 618
        }
    }
}
